### ISSUE TITLE
Setting FTP_CRED_SIZE on the fly like with FTP_BUF_SIZE

### ISSUE THREAD

**Issue by davekc** [khoih-prog/FTP_Server_Teensy41#4]
FTP_CRED_SIZE is defined to 16 (limiting the credentials to 15 characters actually)

What about setting it to 17 by default or...

Being able to set it on the fly like with FTP_BUF_SIZE
```
#if (!defined(FTP_CRED_SIZE))
  #warning Using default FTP_CRED_SIZE = 17
  #define FTP_CRED_SIZE 17
#endif
```

Thanks for the library!

**Comment by davekc** [comment]
Or course it could be implemented differently. Like:
```
char user[FTP_CRED_SIZE +1]; // user name
char pass[FTP_CRED_SIZE +1]; // password
```

Then:
```
if ( strlen( _user ) > 0 && strlen( _user ) <= FTP_CRED_SIZE )
if ( strlen( _pass ) > 0 && strlen( _pass ) <= FTP_CRED_SIZE )
```

Just an idea ;)

Kind regards,
Dave

**Comment by khoih-prog** [comment]
Hi @davekc 

The new [**FTP_Server_Teensy41** v1.2.0](https://github.com/khoih-prog/FTP_Server_Teensy41/releases/tag/v1.2.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/FTP_Server_Teensy41#contributions-and-thanks)

Best Regards,

---

### Releases v1.2.0

1. Add support to `WiFiNINA`, such as `Adafruit Airlift Featherwing`
2. Configurable `user_name` length to max 63 and `user_password` to max 127. Check [**Setting FTP_CRED_SIZE on the fly like with FTP_BUF_SIZE** #4](https://github.com/khoih-prog/FTP_Server_Teensy41/issues/4)
